default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: testapp_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: testapp_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: testapp_production
  # username: myuser
  # password: mypassword
  host: localhost
